# Generated by Django 4.2.1 on 2023-07-05 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sell Price')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salestorages', to='sale.sale', verbose_name='Sale')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salestorages', to='storage.storage', verbose_name='Storage')),
            ],
            options={
                'verbose_name': 'SaleStorage',
                'verbose_name_plural': 'SaleStorages',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='storage',
            field=models.ManyToManyField(related_name='sales', through='sale.SaleStorage', to='storage.storage', verbose_name='Storage'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
