# Generated by Django 4.2.1 on 2023-07-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy price')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sell price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Storage Item',
                'verbose_name_plural': 'Storage',
            },
        ),
    ]
